site_name: PowerPlugins Wiki
site_description: 'A central Wiki for all sorts of information!'
site_author: 'Andre_601'

copyright: |
  This documentation is provided under the 
  <a href="https://github.com/PowerPlugins/Wiki-Docs/blob/master/LICENSE" target="_blank">MIT-License</a>
  <br>Emojis provided with <img alt="❤" class="twemoji md-footer-custom-text" src="https://twemoji.maxcdn.com/v/latest/svg/2764.svg" title="love"> (and for free) by 
  <a href="https://github.com/twitter/twemoji">Twemoji</a>

docs_dir: docs/

repo_name: PowerPlugins/Wiki-Docs
repo_url: https://github.com/PowerPlugins/Wiki-Docs

nav:
  - Welcome: index.md
  - Contribute:
    - Contribute: contributing/index.md
    - Styling: contributing/styling-guide.md
  - Wiki:
    - Welcome: wiki/index.md
    - StatusNPC:
      - StatusNPC: wiki/statusnpc/index.md
      - Commands: wiki/statusnpc/commands.md
      - Colors: wiki/statusnpc/colors.md
    - Formatter Expansion:
      - Formatter Expansion: wiki/formatter-expansion/index.md
      - Locales: wiki/formatter-expansion/locales.md

theme:
  name: 'material'
  custom_dir: 'override'
  favicon: 'assets/img/favicon.png'
  palette:
    primary: 'orange'
    accent: 'yellow'
  features:
  - tabs
  icon:
    logo: octicons/book
    repo: fontawesome/brands/github-square

extra_css:
  - 'assets/css/extra.css'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/PowerPlugins'
    - icon: 'fontawesome/solid/link'
      link: 'https://powerplugins.net'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
